// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RealmConfig Describes the configuration of the ARM CCA Realm.
//
// swagger:model RealmConfig
type RealmConfig struct {

	// The hash algorithm used to verify the Realm's integrity.
	// Enum: ["SHA256","SHA512"]
	HashAlgorithm *string `json:"hash_algorithm,omitempty"`
}

// Validate validates this realm config
func (m *RealmConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHashAlgorithm(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var realmConfigTypeHashAlgorithmPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["SHA256","SHA512"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		realmConfigTypeHashAlgorithmPropEnum = append(realmConfigTypeHashAlgorithmPropEnum, v)
	}
}

const (

	// RealmConfigHashAlgorithmSHA256 captures enum value "SHA256"
	RealmConfigHashAlgorithmSHA256 string = "SHA256"

	// RealmConfigHashAlgorithmSHA512 captures enum value "SHA512"
	RealmConfigHashAlgorithmSHA512 string = "SHA512"
)

// prop value enum
func (m *RealmConfig) validateHashAlgorithmEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, realmConfigTypeHashAlgorithmPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RealmConfig) validateHashAlgorithm(formats strfmt.Registry) error {
	if swag.IsZero(m.HashAlgorithm) { // not required
		return nil
	}

	// value enum
	if err := m.validateHashAlgorithmEnum("hash_algorithm", "body", *m.HashAlgorithm); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this realm config based on context it is used
func (m *RealmConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RealmConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RealmConfig) UnmarshalBinary(b []byte) error {
	var res RealmConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
